Introducción a la Criptografía y a la Seguridad de la información

Juan Carlos Garavito Higuera

Turning Grill Cipher

Implementar el algoritmo de Turning Grille utilizando Python, en donde se reciben los siguientes parámetros:

    Tamaño de la retícula (cuadrada, por ejemplo 2 indica que es de 2x2)
    Dirección de la rotación (sentido de las manecillas del reloj o sentido contrario, por ejemplo 1 ó 0 respectivamente)
    Modo (cifra miento o desciframiento, por ejemplo 1 ó 0 respectivamente)
    Cantidad y distribución de los hoyos (se recomienda ingresar únicamente las celdas de la matriz en la que hay hoyos)
    Mensaje a (de)cifrar

In [1]:
import numpy as np;
def rotate_matrix_90(matrix,right_rotation=True):
  if right_rotation: return np.rot90(matrix, -1)
  else: return np.rot90(matrix)

def filler(matrix,character):
  for row in range(len(matrix)):
    for col in range(len(matrix[row])):
      if matrix[row][col] == "": matrix[row][col] = character;
  return matrix

def turning_grill_cipher(msg, square_grill_size,hole_pos_array, right_rotation = True ,encrypt=True, filler_char="X"):
  grill_total_size = square_grill_size*square_grill_size;
  #Checking if user is an idiot
  if square_grill_size<1:
    raise(Exception("ERROR: Grill dimensions must be at least 1x1"));
  if len(hole_pos_array)>(grill_total_size):
    raise(Exception("ERROR: Number of holes exceeds the grill size."));
  for row, col in hole_pos_array:
    if row < 0 or col < 0 or row > square_grill_size-1 or col > square_grill_size-1:
      raise(Exception("ERROR: Invalid position for hole placement: [{}, {}]".format(row, col)))

  #Processing the input
  processed_msg = ''.join(char.upper() for char in msg if char.isalpha());

  if len(processed_msg) < 1:
    raise(Exception("ERROR: Message must be at least a character long."));
  if len(processed_msg) > (grill_total_size):
    raise(Exception("ERROR: Message exceeds the grill size."));
  if not encrypt and len(msg) != (grill_total_size):
    raise(Exception("ERROR: Message to decrypt has unmatching dimensions with the grill: [{} vs {}]".format(len(msg), grill_total_size)));

  #Creating the grills
  char_matrix = [[''] * square_grill_size for _ in range(square_grill_size)]
  turning_hole_grid = np.zeros((square_grill_size, square_grill_size), dtype=int);
  for row, col in hole_pos_array: turning_hole_grid[row, col] = 1;


  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

  msg = "";
  string_index = 0;
  # ENCRYPTION
  if encrypt:
    for _ in range(4):
      print(turning_hole_grid)
      # Fill character matrix with characters where there are 1's in the turning matrix
      for row in range(square_grill_size):
        for col in range(square_grill_size):
          if turning_hole_grid[row][col] == 1 and string_index < len(processed_msg):
            char_matrix[row][col] = processed_msg[string_index]
            string_index+=1;
      # Rotate the turning hole grid
      turning_hole_grid = rotate_matrix_90(turning_hole_grid,right_rotation);
    char_matrix = filler(char_matrix,filler_char);
    for row in char_matrix: msg += ''.join(row)
    return msg

  # DECRYPTION
  else:
    # Fill character matrix with characters where there are 1's in the turning matrix
    for row in range(square_grill_size):
      for col in range(square_grill_size):
          char_matrix[row][col] = processed_msg[string_index]
          string_index+=1;
    # Decrypt
    for _ in range(4):
      for row in range(square_grill_size):
        for col in range(square_grill_size):
          if turning_hole_grid[row][col] == 1:
            msg+=char_matrix[row][col]
      turning_hole_grid = rotate_matrix_90(turning_hole_grid,right_rotation);
    return msg

In [2]:
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Turning Grill Cipher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")
plain_text = "JIM ATTACKS AT DAWN";
square_grill_size = 4;
hole_pos_array = [(0,0),(2,1),(3,2),(2,3)];
encrypted = turning_grill_cipher(plain_text, square_grill_size, hole_pos_array, right_rotation = False, encrypt = True);
decrypted = turning_grill_cipher(encrypted, square_grill_size, hole_pos_array, right_rotation = False, encrypt = False);
print("PlainText: "+plain_text)
print("Encrypted: "+encrypted)
print("Decrypted: "+decrypted)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Turning Grill Cipher ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[1 0 0 0]
 [0 0 0 0]
 [0 1 0 1]
 [0 0 1 0]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [1 0 0 0]]
[[0 1 0 0]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]
[[0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]]
PlainText: JIM ATTACKS AT DAWN
Encrypted: JKTDSAATWIAMCNAT
Decrypted: JIMATTACKSATDAWN
